#pragma once

#define ERROR_MY_CASINO_HAS_ALREADY_OPERATOR 0x00010001
#define ERROR_MY_CASINO_NO_OPERATOR 0x00010002
#define ERROR_MY_CASINO_CANNOT_LOAD_ACCOUNT 0x00010003

#define ERROR_MY_CASINO_BET_ACCOUNT_BALANCE_NOT_SUFFICIENT 0x00010004



#define BET_DETAILS_PROPTERY_COUNT 3
#define BET_FULL_DETAILS_PROPTERY_COUNT  7

#define TRANSACTION_PROPTERY_COUNT 3

enum MyCasinoTransactionsTypes
{
	DEPOSIT = 0,
	WITHDRAWAL,
	PRELIMINARY,
	BET
};

enum MyCasinoUserTypes {
	Operator = 0,
	Gamer
};