#ifndef RPC_MYCASINO_CONFIG_H
#define RPC_MYCASINO_CONFIG_H

#define MYCASINO_RPC_PROT_SEQ      "ncacn_ip_tcp"
#define MYCASINO_RPC_ENDPOINT      "1200"
#define MYCASINO_RPC_DEF_NETWADDR  "127.0.0.1"

#endif