// COMMyBaySrv.idl : IDL-Quelle für COMMyBaySrv
//

// Diese Datei wird mit dem MIDL-Tool bearbeitet,
// um den Quellcode für die Typbibliothek (COMMyBaySrv.tlb) und den Marshallingcode zu erzeugen.

import "oaidl.idl";
import "ocidl.idl";

typedef SAFEARRAY(VARIANT) SAFEARRAY_VAR;

[
	object,
	uuid(C3E6334F-3574-4001-8DBE-1B549B3877D0),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface ICOMMyBay : IDispatch{
	[id(1)] HRESULT login([in] BSTR username, [in] BSTR password, [out] ULONG* sessionId);
	[id(2)] HRESULT logout([in] ULONG sessionId);
	[id(3)] HRESULT offer([in] ULONG sessionId, [in] BSTR articleName, [in] DOUBLE startBid, [out] ULONG* auctionNumber);
	[id(4)] HRESULT interested([in] ULONG sessionId, [in] ULONG auctionNumber);
	[id(5)] HRESULT getAuctions([in] ULONG sessionId, [in] ULONG flags, [in] BSTR articleName, [out] ULONG* countAuctions, [out] SAFEARRAY_VAR* auctions);
	[id(6)] HRESULT bid([in] ULONG sessionId, [in] ULONG auctionNumber, [in] DOUBLE bidValue);
	[id(7)] HRESULT details([in] ULONG sessionId, [in] ULONG auctionNumber, [out] SAFEARRAY_VAR* allBids, [out] ULONG* countBids);
	[id(8)] HRESULT endauction([in] ULONG sessionId, [in] ULONG auctionNumber);
	[id(9)] HRESULT getMessage([in] ULONG sessionId, [out] BOOL* messageAvailable, [out] ULONG* messageType, [out] SAFEARRAY_VAR* message);
};
[
	uuid(1D44AFF3-01FA-4E73-B830-297A78FF5194),
	version(1.0),
]
library COMMyBaySrvLib
{
	importlib("stdole2.tlb");
	[
		uuid(E591CA8E-1693-4BD0-9A65-919D333389AA)		
	]
	coclass COMMyBay
	{
		[default] interface ICOMMyBay;
	};
};

